data()
View(mtcars)
t=mtcars %>% select(hp,gear)
View(t)
y=mtcars %>% group_by(cyl)%>%summarise(mean=mean(hp),sum=sum(hp),n=n())
View(y)
a1=select(mtcars,hp,cyl)
View(a1)
a2=select(mtcars,disp,drat)
View(a2)
a3=bind_cols(a1,a2)
View(a3)
a4=bind_rows(a1,a2)
View(a4)
a5=union(a1,a2)
View(a5)
b1=filter(mtcars,hp<=120)
b2=filter(mtcars,hp>=100)
c1=union(b1,b2)
View(c1)
c2=intersect(b1,b2)
View(c2)
