#impoting bodyperformance
library(readr)
bodyPerformance <- read_csv("C:/Users/admin/Downloads/bodyPerformance.csv")
View(bodyPerformance)
library(readr)
marketing_campaign_1_ <- read_delim("C:/Users/admin/Downloads/marketing_campaign (1).csv", 
                                    delim = "\t", escape_double = FALSE, 
                                    trim_ws = TRUE)
View(marketing_campaign_1_)
bodyPerformance <-data.frame(bp)
str(bp)
View(bodyPerformance)
MC1 = select(marketing_campaign_1_,ID,Year_Birth)
View(MC1)
MC2 = select(bodyPerformance,age:gender)
View(MC2)
MC3=select(marketing_campaign_1_,-AcceptedCmp3:-AcceptedCmp2)
View(MC3)
#contains(bodyPerformance,M, ignore.case = T, logic = “or”, switch = F)
w=filter(bodyPerformance,gender=="M")
View(w)
u=select(marketing_campaign_1_,ID,Marital_Status)
d=filter(u,Marital_Status=="Single")
View(d)
View(u)
s=mutate(bodyPerformance,RATIO=height_cm/weight_kg)
View(s)
ager=mutate(marketing_campaign_1_,AGE=2022-Year_Birth)
View(ager)
rt=marketing_campaign_1_%>%summarise(median=median(Year_Birth),variance=var(Year_Birth))
View(rt)
#rr=arrange(marketing_campaign_1_,Year_Birth)
rr=arrange(marketing_campaign_1_,Income)
View(rr)
